name: Nightly Dry-Run

on:
  schedule:
    # Run at 02:00 UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  nightly-run:
    name: Nightly System Test
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run nightly system test
        env:
          DRY_RUN: true
          BROKER_NAME: binance
          BINANCE_BASE_URL: https://testnet.binance.vision
        run: |
          python scripts/nightly_run.py
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: nightly-test-results
          path: |
            logs/
            data/session/
          retention-days: 30
      
      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 Nightly Test Failed - ' + new Date().toISOString().split('T')[0];
            const body = `Nightly dry-run test failed. Please review the logs.
            
            **Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['nightly-failure', 'needs-review']
            });
